# Generated by Django 5.2.4 on 2025-10-17 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heure', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField()),
                ('Prenom', models.CharField()),
                ('Droit', models.BooleanField(default=False)),
                ('Dossier', models.BooleanField(default=False)),
                ('Profile', models.ImageField(default='default.jpg', upload_to='static/profile')),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField()),
                ('duree', models.IntegerField()),
                ('level_number', models.IntegerField()),
                ('Ecolage', models.IntegerField()),
                ('Type_Formations', models.CharField()),
                ('cours_semaine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emplois_du_temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jour_de_la_semaine', models.CharField()),
                ('Niveau', models.CharField()),
                ('Eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.eleve_class')),
                ('Heure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.disponibilite')),
                ('type_de_Formations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.formations')),
            ],
        ),
        migrations.CreateModel(
            name='Formations_eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Niveau', models.CharField()),
                ('Reste_mois', models.IntegerField()),
                ('Eleve_choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.eleve_class')),
                ('Formations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.formations')),
            ],
        ),
        migrations.CreateModel(
            name='Mois_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField()),
                ('Ecolage', models.BooleanField(default=False)),
                ('Ecolage_payer', models.FloatField(default=0)),
                ('Niveau', models.CharField()),
                ('Eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.eleve_class')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau_Par_Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Niveaux', models.CharField()),
                ('FK_formations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.formations')),
            ],
        ),
    ]
