# Generated by Django 5.2.4 on 2025-10-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mois_class',
            name='Formations',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Eleve.formations'),
            preserve_default=False,
        ),
    ]
