# Generated by Django 5.2.7 on 2025-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eleve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formations',
            name='Droit',
            field=models.IntegerField(default=30000),
        ),
    ]
