# Generated by Django 5.2.4 on 2025-10-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eleve', '0002_mois_class_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve_class',
            name='Numero',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
