# Generated by Django 5.2.4 on 2025-10-21 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eleve', '0003_eleve_class_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve_class',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
