# Generated by Django 5.2.7 on 2025-10-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eleve', '0004_eleve_class_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplois_du_temps',
            name='cles_unique',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
