# Generated by Django 5.2.7 on 2025-10-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eleve', '0005_emplois_du_temps_cles_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='mois_class',
            name='Numero_fa',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
