# Generated by Django 5.2.7 on 2025-11-05 09:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eleve', '0001_initial'),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Cin', models.CharField(max_length=20)),
                ('Duree', models.CharField(max_length=50)),
                ('Date_embauche', models.DateField(default=datetime.datetime.now)),
                ('Payement', models.FloatField()),
                ('Status', models.BooleanField(default=True)),
                ('Types_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eleve.formations')),
            ],
        ),
        migrations.CreateModel(
            name='Prof_Mois_payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mois', models.CharField()),
                ('Years_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.annee_class')),
            ],
        ),
        migrations.CreateModel(
            name='Prof_Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_day', models.FloatField(default=0)),
                ('Seance_Hours', models.FloatField(default=0)),
                ('Total_Salary_month', models.FloatField(default=0)),
                ('Observations', models.CharField()),
                ('Status', models.CharField(default=False)),
                ('Mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProf.prof_mois_payement')),
                ('Prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProf.prof_models')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.annee_class')),
            ],
        ),
    ]
